### ISSUE TITLE
Support in ARM64 Ubuntu 22.04 ROS2 humble

### ISSUE THREAD

**Issue by anfederman** [christianrauch/raspicam2_node#13]
Have you tried this out yet on a PI4 running ARM64 Ubuntu 22.04?

I think the instructions wont work since oi_flavor makers don't work and you can get the libraspberrypi's to build.

**Comment by christianrauch** [comment]
No. I never got the camera working on Ubuntu. Anyway, this form of accessing the camera on a Raspberry Pi is deprecated. You should use `libcamera` for that.

I have an experimental node (https://github.com/christianrauch/camera_ros) for this, but I also was not able to use libcamera on Ubuntu.

**Comment by anfederman** [comment]
Hey thanks. Ditto for me on libcamera on the Pi. v4l2-ctrl sees the piccam
as does libcamera, but it can't stream. I get ioctl, timing or format
errors. The config.txt has a auto detect camera feature. When on it sees
the camera as CSI, but off as mmal.

  I did get Raspicam to work on 20.04 ARM64 by building userland, getting
/opt/vc built. Raspistill would then work.

If I could answer the question: Why doesn't cheese see the CSI camera? I
might understand what the issue is.

**Comment by anfederman** [comment]
PS, I have a friend here in the US, Marco Walther, who has had some success
with camera_ros on Ubuntu 22.

**Comment by mw46d** [comment]
Ubuntu 22.04 sits on too old a source base for libcamera:-( I took the current sources from the libcamera repo and that seems to work better. I'm currently trying to build packages out of that source tree and the libcamera_apps but there are some parts of the installation, which the package does not like yet:-(

**Comment by christianrauch** [comment]
libcamera is moving fast and does not have a stable API (yet). You either have to use the library and apps from the Ubuntu repo or you have to use the most recent source versions together.

**Comment by anfederman** [comment]
sudo rpi-update and build from libcamera git haven't resolved situation.
Thanks for your suggestions.

libcamera-hello stil gives:

0:07:42.467248093] [1980]  INFO RPI raspberrypi.cpp:759 Sensor:
***@***.******@***.*** - Selected sensor format:
1640x1232-SBGGR10_1X10 - Selected unicam format: 1640x1232-pBAA
[0:07:43.518041393] [1980] ERROR V4L2 v4l2_videodevice.cpp:1867
/dev/video0[12:cap]: Failed to start streaming: Input/output error
ERROR: *** failed to start camera ***

***@***.***:~$ libcamera-hello --version
libcamera-apps build: 67d4e9294d61-intree 01-08-2022 (09:52:16)
libcamera build: v0.0.0+3777-69ae75b0

uname -a
Linux ubiq22-desktop 5.15.0-1012-raspi #14-Ubuntu SMP PREEMPT Fri Jun 24
13:10:28 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
history

**Comment by anfederman** [comment]
Darn it! Problem solved. Cable on the camera was too long. Short cable
fixed problem. Libcamera-hello working. So is camera_ros

**Comment by anfederman** [comment]
It's always something.   :- )))

Sent from Yahoo Mail on Android 
 
  On Wed, Aug 3, 2022 at 11:33 AM, Alan ***@***.***> wrote:   Darn it! Problem solved. Cable on the camera was too long. Short cable fixed problem. Libcamera-hello working. So is camera_ros
On Tue, Aug 2, 2022, 6:39 PM Alan Federman ***@***.***> wrote:

sudo rpi-update and build from libcamera git haven't resolved situation. Thanks for your suggestions.
libcamera-hello stil gives:
0:07:42.467248093] [1980]  INFO RPI raspberrypi.cpp:759 Sensor: ***@***.******@***.*** - Selected sensor format: 1640x1232-SBGGR10_1X10 - Selected unicam format: 1640x1232-pBAA
[0:07:43.518041393] [1980] ERROR V4L2 v4l2_videodevice.cpp:1867 /dev/video0[12:cap]: Failed to start streaming: Input/output error
ERROR: *** failed to start camera ***

***@***.***:~$ libcamera-hello --version
libcamera-apps build: 67d4e9294d61-intree 01-08-2022 (09:52:16)
libcamera build: v0.0.0+3777-69ae75b0

uname -a
Linux ubiq22-desktop 5.15.0-1012-raspi #14-Ubuntu SMP PREEMPT Fri Jun 24 13:10:28 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
history
On Tue, Aug 2, 2022 at 1:21 PM Christian Rauch ***@***.***> wrote:




libcamera is moving fast and does not have a stable API (yet). You either have to use the library and apps from the Ubuntu repo or you have to use the most recent source versions together.

**Comment by christianrauch** [comment]
Good that you found the error. For generic libcamera issues, I recommend that you check https://forums.raspberrypi.com or https://raspberrypi.stackexchange.com as this repo is not related to libcamera and I plan to deprecate it at some point.
