### ISSUE TITLE
Release plan?

### ISSUE THREAD

**Issue by AAlon** [christianrauch/raspicam2_node#2]
Hello, I was wondering whether you had any plans for releasing a stable 1.0.0 version and blooming this package for Dashing...?

Thanks.

**Comment by christianrauch** [comment]
I haven't worked on dashing support yet. I intend to work on this in the short-term after I managed to cross-compile dashing for Raspbian.
But I am also happy to review a PR that ports the node to dashing :-) 

I don't think it's possible to bloom the node since it depends on some Broadcom libraries that are provided with Raspbian and Raspbian is unfortunately not a target of the ROS buildfarm.

**Comment by AAlon** [comment]
Thanks for the quick response. You don't necessarily need to cross compile dashing yourself, there's a fat armhf archive of ROS2 core (I know there used to be one that was supposed to be armhf but was in fact arm64, that problem was fixed - it's now really armhf). Not sure if it works on Raspbian out of the box though.

**Dashing:** I don't have time for it at the moment but it should be fairly simple? I don't remember major changes when moving from crystal to dashing for relatively simple nodes. For parameters you'd have to either call `declare_parameter` or provide node options which allow undeclared parameters, e.g.:
```
    rclcpp::NodeOptions node_options;
    node_options.allow_undeclared_parameters(true);
    node_options.automatically_declare_parameters_from_overrides(true);
```

**Bloom:** there should be a way to do this - the raspicam exists as binary in Kinetic: https://github.com/ros/rosdistro/blob/master/kinetic/distribution.yaml#L10330
I guess they have conditional compilation depending on the target platform; not sure how the buildfarm handles RPi builds correctly. Also, it doesn't have to be specific for Raspbian - the raspicam node for ROS1 also works on Ubuntu 16.04 and 18.04, provided you have set up the relevant drivers / userland utilities (like in the pi-flavor-maker images: https://ubuntu-pi-flavour-maker.org/blog/).

**Comment by christianrauch** [comment]
I had a look at that armhf archive too, but it's compiled for Ubuntu 18.04 armhf to run on Raspberry Pi 2 and upwards (https://github.com/ros2/ros2/issues/721#issuecomment-508587329). It won't run on Raspbian on a RPi1. In the meantime, I managed to compile ROS2 directly on Raspbian and I will have a look at porting the node to dashing shortly.

The original `raspicam_node` uses a stup to compile on x86: https://github.com/UbiquityRobotics/raspicam_node/blob/195694afee514370aaf28712e1e09c48bdaf2af7/src/raspicam_node.cpp#L29-L38. I am not aware of a CI job for Raspbian targets. The rosdistro entry only has the `doc` key but no `release`, and there is no released package in http://packages.ros.org/ros/ubuntu/dists/xenial/main/binary-armhf/Packages.

I could bloom a generic package for armhf targets, i.e. for the Ubuntu armhf target you mentioned, but it would still miss some of the Broadcom libraries on Raspbian that are not available on Ubuntu. If someone manages to release the dependencies (basically everythin in `/opt/vc/`) to ROS2, I am happy to bloom this node.

**Comment by christianrauch** [comment]
@AAlon I pushed dashing support to master. Give it a try and let me know.
