### ISSUE TITLE
ROS2 Foxy - build fails

### ISSUE THREAD

**Issue by nplan** [christianrauch/raspicam2_node#5]
OS: Raspbian GNU/Linux 10 (buster)
Platform: Raspberry Pi 4
ROS2 Foxy built from source

`colcon build` fails with the following error:

```
--- stderr: raspicam2                             
/home/pi/dev_ws/src/raspicam2_node/src/RasPiCamPublisherNode.cpp:151:10: fatal error: rclcpp_components/register_node_macro.hpp: No such file or directory
 #include <rclcpp_components/register_node_macro.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

If I comment lines:
```
#include <rclcpp_components/register_node_macro.hpp>
RCLCPP_COMPONENTS_REGISTER_NODE(RasPiCamPublisher)
```

in `RasPiCamPublisherNode.cpp` the build finsihes and node can be run. But I am not able to view image topic using rviz2 or rqt_image_view - the image is blank.

**Comment by christianrauch** [comment]
Does `sudo apt install ros-foxy-rclcpp-components` fix the issue?

Package `rclcpp_components` is listed as a dependency. So a `rosdep install --from-paths src --ignore-src` should install all dependencies.

**Comment by nplan** [comment]
`sudo apt install ros-foxy-rclcpp-components` is unable to find the package, because I'm using raspbian. I believe `rclcpp_components` were installed together with my ros2 instalation. I can see the files at: `~/ros2_foxy/install/rclcpp_components`

`rosdep` returned `#All required rosdeps installed successfully` without installing anything.

This is a strange issue because I was able to successfuly build and run `ros2/demos/image_tools` which also include from `rclcpp_components`

**Comment by nplan** [comment]
I modified line 38 in CMakeLists.txt to include `rclcpp_components`
```
 ament_target_dependencies(RasPiCamPublisherNode rclcpp rclcpp_components sensor_msgs class_loader)
```
Now the build finishes.

**Comment by christianrauch** [comment]
> I modified line 38 in CMakeLists.txt to include `rclcpp_components`
> 
> ```
>  ament_target_dependencies(RasPiCamPublisherNode rclcpp rclcpp_components sensor_msgs class_loader)
> ```
> 
> Now the build finishes.

Right. It was missing as an ament dependency. I am surprised that this worked before. Maybe there was some logic in `rclcpp_components_register_nodes` that added includes and libraries.

Can you submit a pull request that fixes the issue?

**Comment by christianrauch** [comment]
Fixed by https://github.com/christianrauch/raspicam2_node/pull/6.
